### ISSUE TITLE
404图片显示的bug

### ISSUE THREAD

**Issue by chenneal** [miiiku/flex-block#13]
flex-block自带一个404图片功能，发现第一次刷新页面显示正常，后续在再刷就刷不出来了。

第一次：

![image](https://user-images.githubusercontent.com/7855327/82784800-d9391780-9e93-11ea-88d6-1969e86d389d.png)

第二次

![image](https://user-images.githubusercontent.com/7855327/82784819-e3f3ac80-9e93-11ea-8d26-0a9f535b1228.png)

错误链接

https://blog.mipa.site/2017/03/262112.html

**Comment by miiiku** [comment]
诶，你说的大象那个404图片吗，我没弄过这个图片，这有没有可能是你图床的404默认图呢

= =

**Comment by chenneal** [comment]
> 诶，你说的大象那个404图片吗，我没弄过这个图片，这有没有可能是你图床的404默认图呢
> 
> = =

不是啊，这个是我自己换的，和内容无关，用你默认的“fuck you”也是一样的，我就是受不了"fuck you"才换的，哈哈.......

**Comment by miiiku** [comment]
哈哈哈，我知道了，那个默认图片代码那块是我当时临时起意写的，不够规范，导致这个原因好像是图片缓存了所以没有监听到error事件，近期会修改下。

[https://github.com/miiiku/flex-block/blob/ae5fa226829c6201e53cce7cfaf049a33c875007/source/js/script.js#L36](https://github.com/miiiku/flex-block/blob/ae5fa226829c6201e53cce7cfaf049a33c875007/source/js/script.js#L36)

**Comment by chenneal** [comment]
话说，你主页的INS标签啥时候上啊

**Comment by miiiku** [comment]
诶，暂时没打算上，毕竟自己定制化的东西比较多，上到主题文件上感觉不适合
