### ISSUE TITLE
首页模块cover和subtitle显示

### ISSUE THREAD

**Issue by CHAsencenge** [miiiku/flex-block#15]
在配置和时候遇到以下疑问
1. 首页的各个文章对应的模块如何添加cover？（如预览图1所示）
2.Front-matter其余部分如cover、type等均可正常使用，但subtitle无法显示（一直为默认的名称加时间），请问是否有限定的格式？

**Comment by miiiku** [comment]
文章对应的模块你的意思是文章分类吗，那个用的是首页的模版，所以不能添加cover。

subitlte无法显示的问题是subtitle只支持自定义页面，文章内容页面是没有的，也就是你给_post/目录下的文章添加subtitle是没有效果的。

**Comment by CHAsencenge** [comment]
第二个问题的解答理解了，第一个我是指在首页每一篇文章会对应一个card-item，readme中的第一个预览图有三篇文章，前两篇和第三篇的显示区别，我查看了我的根目录下的index.html
`<div class="card-item img">
            <article>
              
                <div class="card-cover" style="background-image: url(cover.jpg)"></div>
              
              
                <a class="article-link card-link" href="/2020/07/14/xxx/" itemprop="url"></a>
              
              <h2 class="article-title">xxx</h2>
              <div class="article-meta">
                <strong>CHAsencenge</strong>
                <span>发布于</span>
                
  <a href="/2020/07/14/xxx/" class="article-date">
    <time datetime="2020-07-14T14:30:06.000Z" itemprop="datePublished">2020-07-14</time>
  </a>`
在card-cover中其实是有url(cover.jpg)的,但实际在主页还是默认的样式。
所以想确认一下，在Front-Matter中添加的cover会不会自动同步到主页界面的对应文章的card-item上？

**Comment by HeyBreezeYang** [comment]
大佬您好， 皮肤主题 渲染的时候遇到一些问题请教，
    1   :   在非主业页面如何渲染，我测试了下如果是用的 hexo new page 页面，那么页面下会生成相应的index.md 文件，渲染的时候渲染为对应的index .html 文件，但是我这个页面没有内容呢，依旧是一个头，然后没有下面的内容，我想在其他页面写点其他东西，
    2 ： 关于歌曲连接， 因为我没有用七牛 ，所以链接不了七牛上的资源，我试了网易云音乐，不行，还有视频播放器的， 也不支持其他，请问问如何链接其他资源，如果我用本地服务器上的资源呢？ 
   3： 如果我想添加一点其他原生HTML代码，在哪里插入，或者引入，例如JS 动画效果那种？  
感谢解答

**Comment by miiiku** [comment]
> 第二个问题的解答理解了，第一个我是指在首页每一篇文章会对应一个卡片项目，readme中的第一个预览图有三篇文章，前两篇和第三篇的显示区别，我查看了我的根目录下的index.html的
> `
> 
> 
> ```
>             <div class="card-cover" style="background-image: url(cover.jpg)"></div>
>           
>           
>             <a class="article-link card-link" href="/2020/07/14/xxx/" itemprop="url"></a>
>           
>           <h2 class="article-title">xxx</h2>
>           <div class="article-meta">
>             <strong>CHAsencenge</strong>
>             <span>发布于</span>
> ```
> 
> [ 2020-07-14` ](/2020/07/14/xxx/)在card-cover中其实是有url（cover.jpg）的，但实际在主页还是图案的样式。所以想确认一下，在Front-Matter中添加的cover会不会自动同步到主页界面的对应文章的card-item上？

在Front-Matter中设置的cover是会在主页卡片上生效的，如果设置的cover图片路径不对或者没有设置，那么就是一个纯色的渐变色背景，如果你设置了cover而没有生效，哪你可以检查一下图片路径是否正确。

**Comment by miiiku** [comment]
> 大佬您好， 皮肤主题 渲染的时候遇到一些问题请教，
> 1 : 在非主业页面如何渲染，我测试了下如果是用的 hexo new page 页面，那么页面下会生成相应的index.md 文件，渲染的时候渲染为对应的index .html 文件，但是我这个页面没有内容呢，依旧是一个头，然后没有下面的内容，我想在其他页面写点其他东西，
> 2 ： 关于歌曲连接， 因为我没有用七牛 ，所以链接不了七牛上的资源，我试了网易云音乐，不行，还有视频播放器的， 也不支持其他，请问问如何链接其他资源，如果我用本地服务器上的资源呢？
> 3： 如果我想添加一点其他原生HTML代码，在哪里插入，或者引入，例如JS 动画效果那种？
> 感谢解答

1.你新生成的页面，如果你要往里面添加内容，那么你直接编辑你生成的那个目录下的index.md就可以了。

2.一般来说只要是以.mp3结尾或者.mp4结尾的链接，都是可以在音乐/视频播放器里播放的，跟七牛没有关系，你也可以吧音乐/视频资源放你博客资源目录下，用相对路径来使用。

3.如果你要添加/修改HTML，那你要找到`/theme/flex-block/layout`目录下，所有的主题HTML模版都在这个目录下，如果想添加JS代码，可以在`flex-block/layout/_partial/footer-other.ejs`这个文件下添加

**Comment by CHAsencenge** [comment]
我也觉得应该是同步的，但是很奇怪，cover在文章页生效，在主页卡片却不显示，我再检查一下吧orz

**Comment by miiiku** [comment]
如果设置了没生效，可以F12开发者工具 -> 审查元素，找到对应的`.card-cover`，看下`background-image`这个属性的图片地址，鼠标右键新窗口打开，看能否正常显示。

**Comment by HeyBreezeYang** [comment]
是的，我是直接编辑的 页面下的index.md . 比如hexo new page about，   vim  source/aobut/index.md     编辑之后，渲染之后没有效果，还是空的页面，只有头部，和图片，主体还是空的，没有渲染到？ 是有js冲突吗，还是有皮肤的开关？

**Comment by miiiku** [comment]
> 是的，我是直接编辑的 页面下的index.md . 比如hexo new page about， vim source/aobut/index.md 编辑之后，渲染之后没有效果，还是空的页面，只有头部，和图片，主体还是空的，没有渲染到？ 是有js冲突吗，还是有皮肤的开关？

没有遇到过你所说的这种情况，如果是本地的话，试试删除缓存。

```
hexo clean

hexo s
```

**Comment by HeyBreezeYang** [comment]
尝试过，没有效果

**Comment by miiiku** [comment]
> 尝试过，没有效果

贴一下你idnex.md的内容呢。

**Comment by HeyBreezeYang** [comment]
刚刚重启了下服务器，再渲染又可以了。。。。

**Comment by miiiku** [comment]
> 刚刚重启了下服务器，再渲染又可以了。。。。

好的吧。
