### ISSUE TITLE
关于LaTeX公式的使用问题

### ISSUE THREAD

**Issue by Anastasiawangyx** [miiiku/flex-block#16]
你好呀，刚开始使用hexo，看到你的主题很漂亮，所以就拿下来用了，还是非常感谢你制作出来这么好看的主题❤️❤️
但是我想在我的文章里插入LaTeX公式的时候，好像出了一点问题。我按照网上给出的教程在目录下npm了几个包，然后发现主题的_config.yml文件下好像没有mathjax支持，我手动添加了之后发现LaTeX公式在我本地的md编辑器上显示的很好，但依旧无法显示在博客上，倒腾了很久也没找到办法，希望你能帮助我一下，万分感谢🙏
顺便贴一下我在网上找到的教程：https://blog.csdn.net/weixin_43318626/article/details/89407031

**Comment by seeleclover** [comment]
你好，我也是flex-block主题的用户之一，刚开始也是被这个主题给迷上了。
关于插入LaTex公式，我的解决方案是借助[www.latexlive.com](https://www.latexlive.com/)这个网站。

**Comment by seeleclover** [comment]
> 你好呀，刚开始使用hexo，看到你的主题很漂亮，所以就拿下来用了，还是非常感谢你制作出来这么好看的主题❤️❤️
> 但是我想在我的文章里插入LaTeX公式的时候，好像出了一点问题。我按照网上给出的教程在目录下npm了几个包，然后发现主题的_config.yml文件下好像没有mathjax支持，我手动添加了之后发现LaTeX公式在我本地的md编辑器上显示的很好，但依旧无法显示在博客上，倒腾了很久也没找到办法，希望你能帮助我一下，万分感谢🙏
> 顺便贴一下我在网上找到的教程：https://blog.csdn.net/weixin_43318626/article/details/89407031

你好，我也是flex-block主题的用户之一，刚开始也是被这个主题给迷上了。
关于插入LaTex公式，我的解决方案是借助www.latexlive.com这个网站。

**Comment by seeleclover** [comment]
> 你好呀，刚开始使用hexo，看到你的主题很漂亮，所以就拿下来用了，还是非常感谢你制作出来这么好看的主题❤️❤️
> 但是我想在我的文章里插入LaTeX公式的时候，好像出了一点问题。我按照网上给出的教程在目录下npm了几个包，然后发现主题的_config.yml文件下好像没有mathjax支持，我手动添加了之后发现LaTeX公式在我本地的md编辑器上显示的很好，但依旧无法显示在博客上，倒腾了很久也没找到办法，希望你能帮助我一下，万分感谢🙏
> 顺便贴一下我在网上找到的教程：https://blog.csdn.net/weixin_43318626/article/details/89407031

你好，我也是flex-block主题的用户之一，刚开始也是被这个主题给迷上了。
我也遇到过和你同样的问题。
关于插入LaTex公式，我的解决方案是借助[www.latexlive.com](https://www.latexlive.com/)这个网站，生成SVG code再嵌入进md文件。

**Comment by miiiku** [comment]
你好，目前这个主题是不支持LaTeX公式的，可以先使用 @seeleclover 所提供的方案导出svg放入文章，如果要主题支持，需要改markdown的渲染引擎，后续看下需否需要加上对LaTeX公式的支持。

**Comment by MakerGYT** [comment]
@miiiku @seeleclover @Anastasiawangyx 可以试试[markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img),自动将latex公式转化为图片，服务端渲染，稳定可靠
### 安装
```sh
npm un hexo-renderer-marked --save
npm i hexo-renderer-markdown-it markdown-it-latex2img --save
```
### 配置
```yml
# _config.yml
markdown:
  plugins:
    - markdown-it-latex2img
```

**Comment by ArmandXiao** [comment]
兄弟们试试这个！！
在这个 theme 的 layout 文件夹里
找到 `layout,ejs`

放在 <head></head> 之间就行！
https://armandxiao.github.io/2020/10/02/Hexo-GitHub-%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0/#Latex

```
<!--将该代码放入博客模板的head中即可-->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
tex2jax: {
inlineMath: [['$','$'], ['\\(','\\)']],
processEscapes: true
}
});
</script>
<!--latex数学显示公式-->
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

**Comment by Anastasiawangyx** [comment]
> 兄弟们试试这个！！
> 在这个 theme 的 layout 文件夹里
> 找到 `layout.ejs`
> 
> 放在 之间就行！
> https://armandxiao.github.io/2020/10/02/Hexo-GitHub-%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0/#Latex
> 
> ```
> 
> <script type="text/x-mathjax-config">
> MathJax.Hub.Config({
> tex2jax: {
> inlineMath: [['$','$'], ['\\(','\\)']],
> processEscapes: true
> }
> });
> </script>
> 
> <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
> ```

解决了！感谢大兄得！！
