### ISSUE TITLE
无法支持中文toc真的痛苦

### ISSUE THREAD

**Issue by ArmandXiao** [miiiku/flex-block#17]
不知道能不能找到 toc的文件

**Comment by miiiku** [comment]
目前是没有这个功能的，可以尝试使用`hexo-toc`这个插件来生成。

**Comment by ArmandXiao** [comment]
> 目前是没有这个功能的，可以尝试使用`hexo-toc`这个插件来生成。

好滴 学习!!(u‿ฺu✿ฺ)
