### ISSUE TITLE
为该主题进行简单的wordpress主题移植以及部分问题

### ISSUE THREAD

**Issue by dangjinghao** [miiiku/flex-block#21]
这是库
https://github.com/dangjinghao/flex-block-wp
另外，目前有做评论区和404页面的打算么，我在目录中未发现404页面（并不只是因为自己不会做页面）
css/fonts中的Source Han Sans.ttf字体我似乎没在页面中发现引用，请问该字体是否正在使用？

**Comment by miiiku** [comment]
暂时可能不会有啥更新，目前事情比较多，没有太多时间。

Source Han Sans.ttf这个字体并没有用到，只是当时有像尝试引入，但是发现加载时间太长也没深入就放弃了。
