### ISSUE TITLE
分类和标签页展示空白

### ISSUE THREAD

**Issue by outtimes** [miiiku/flex-block#22]
根据readme提示创建了type为 categories和tags的页面，但访问时页面只有标题没有内容。
已经hexo clean清理过缓存了，仍然没有变化。

**Comment by seeleclover** [comment]
请问你的categories的页面的路径是/source/categories/index.md吗？
tags的页面的路径是/source/tags/index.md吗？

然后再检查一下你这两个md文件的内容是否与下面类似：
```
---
title: Tags
date: 2021-01-01 00:00:00
subtitle: 标签云
cover:
type: tags
---
```

[我的博客](https://blog.seeleclover.com/)这两个页面是正常的，你可以看下

**Comment by outtimes** [comment]
感谢回复。检查过了，内容与路径均相符，并且我有在readme看到一次更新：
```
2020.07

添加主题模式(暂不支持手动切换，根据系统自动切换)

删除 分类，标签 页面

UI部分更新
```
经过测试，我站点支持切换深色，而您的不行，估计是作者删除了。

**Comment by seeleclover** [comment]
我再次检查后发现确实如你所说的那样，我是2020年8月才开始使用flex-block主题，但经过代码对比后发现我当初是在Release那里下载的（作者现在应该是把Release的版本全部删了）
如果你想使用categories和tags页，你可以尝试clone之前这个没有删除分类、标签页的版本[fix #12   May 18, 2020](https://github.com/miiiku/flex-block/tree/ae5fa226829c6201e53cce7cfaf049a33c875007)，或对比代码差异并将有影响的部分进行局部修改

**Comment by seeleclover** [comment]
我再次检查后发现确实如你所说的那样，我是2020年8月才开始使用flex-block主题，但经过代码对比后发现我当初是在Release那里下载的（作者现在应该是把Release的版本全部删了）

如果你仍然想使用categories和tags页，你可以尝试clone之前这个不受影响的版本，或对比代码差异并将有影响的部分进行局部修改

> [fix #12](https://github.com/miiiku/flex-block/commit/ae5fa226829c6201e53cce7cfaf049a33c875007) 
> May 18, 2020 
> [< >](https://github.com/miiiku/flex-block/tree/ae5fa226829c6201e53cce7cfaf049a33c875007)

**Comment by outtimes** [comment]
好的，非常感谢你的帮助！
