### ISSUE TITLE
不懂大佬  css 为何不叫 xxx.css  scss    或者.style 也行啊。 styl 有点怪怪的

### ISSUE THREAD

**Issue by gogHeroDream** [miiiku/flex-block#23]

**Comment by miiiku** [comment]
因为使用的是stylus，它也是css预处理器，跟SASS，SCSS一个性质，它的文件后缀名就是.styl。

至于为什么要用它是因为hexo默认使用的就是它，所以我也就没有改用SASS，SCSS等其他CSS预处理器。
