### ISSUE TITLE
列表CSS等问题

### ISSUE THREAD

**Issue by ChinaKevinLi** [miiiku/flex-block#3]
1. 在处理标签的时候，把列表的显示样式设置为了list-style: none，导致文章中的有序列表的标号无法正常显示。建议在标签列表处单独设置list-style: none。
2. 网站icon的说明建议添加到readme之中，需要在主题文件夹内替换修改。
3. 建议删除.DS_Store，这个文件毫无作用。
4. Dplayer会寻找DPlayer.min.css.map和DPlayer.min.js.map文件，在调试工具内会看得到404错误，建议把这两个文件放到lib里面去。
5. 很棒的主题，爱了。

**Comment by miiiku** [comment]
1. 在文章的内容样式中，已经重新单独给无序，有序列表添加了样式。
2. 已将如果修改favicon图标添加到README中。
3. 这个文件是Mac下自动生成到，已经删除。
4. 我这里没有遇到这个问题，但是我还是在lib目录下添加了这两个.map文件，希望对你有用。
5. 谢谢你的肯定！
