### ISSUE TITLE
waterfall为什么只能设置一个，第二个排版就出错了

### ISSUE THREAD

**Issue by chenneal** [miiiku/flex-block#6]
连续放两个

{% waterfall %}
{% endwaterfall %}

{% waterfall %}
{% endwaterfall %}

第二个显示就异常了，这是什么原因？

**Comment by chenneal** [comment]
看了代码，原因是因为waterfall这个项目用classname做id创建项目，好奇怪啊，不是应该用dom为单位创建才对吗。

**Comment by miiiku** [comment]
当时做都时候没考虑到会放多个瀑布流😂😂😂

**Comment by miiiku** [comment]
空了会改一下，目前没太多空闲时间，如果你比较着急可以自己改下代码，抱歉～

**Comment by chenneal** [comment]
@miiiku  真的改的话需要改waterfall项目并上传npm库吧，太麻烦了，我用了一个临时方案，定义了一个虚拟类做标签（用ID参数合成的），每个waterfall有两个类，暂时解决了。

**Comment by miiiku** [comment]
已经解决🥶🥶🥶
