### ISSUE TITLE
怎么增加搜索框

### ISSUE THREAD

**Issue by NChilton** [miiiku/flex-block#7]
这个博客主题很美观，特别适合图片展览。
请问怎么增加搜索框？

**Comment by miiiku** [comment]
诶，目前是没有搜索这个功能的。。 🤒

**Comment by TsingSu** [comment]
如果想往flex-block里加入搜索功能，有什么方法或推荐嘛

**Comment by miiiku** [comment]
@TsingSu 可以试试`hexo-generator-search`这个包

**Comment by TsingSu** [comment]
> @TsingSu 可以试试hexo-generator-search这个包

 谢谢  我加入进去了。
