### ISSUE TITLE
关于flex-block主题锚链接失效问题

### ISSUE THREAD

**Issue by TsingSu** [miiiku/flex-block#8]
在使用flex-block主题搭建博客往文章内加入目录时发现无法实现锚链接无法跳转到同页面的锚点。
代码如下：

`<h1 id="标题1"><a href="#标题1" class="headerlink" title="标题1" ></a>标题1</h1>
其他HTML代码... ...
<a class="toc-link" href="#标题1"><span class="toc-text">标题1</span></a>`

以上代码在Hexo默认主题landscape上可以使用，可以实现锚链接跳转到同页面的锚点的效果。

**Comment by miiiku** [comment]
这是`smoothScroll.js`处理中文锚点时的一个BUG，在`APlayer`中使用到了它。

具体可查看issues [https://github.com/MoePlayer/APlayer/issues/217](https://github.com/MoePlayer/APlayer/issues/217)
