### ISSUE TITLE
遇到的一个问题

### ISSUE THREAD

**Issue by shiinayuki** [miiiku/flex-block#9]
我试了很久，语言怎么设置顶部导航栏也不会变，想问下是要怎么设置顶部导航栏的语言

**Comment by miiiku** [comment]
导航栏的文字并没有加入多语言设置中，需要自己手动改。

**Comment by HeyBreezeYang** [comment]
看了所有的源码，不知道音乐插件和视频插件怎么插的，还有想改下首页布局，也暂时没找到首页布局的代码，建议出个 文档，对，我喜欢改代码，不想写代码，就是这么懒 ，emmmm

**Comment by HeyBreezeYang** [comment]
坐等

**Comment by miiiku** [comment]
> 看了所有的源码，不知道音乐插件和视频插件怎么插的，还有想改下首页布局，也暂时没找到首页布局的代码，建议出个 文档，对，我喜欢改代码，不想写代码，就是这么懒 ，emmmm

aplery和dplayer的js初始化代码分别在`flex-block/layout/plug-in/aplery.ejs`和`flex-block/layout/plug-in/dplayer.ejs`。插入播放器标签代码是在`flex-block/scripts/index.js`。

首页的布局不知道你具体说的是那一块，不过应该在`flex-block/layout/_partial/`这个目录下。

**Comment by HeyBreezeYang** [comment]
已经找到了， 谢谢博主
